version: "3"

services:
  ponto-api:
    container_name: ponto-api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ".env"
    volumes:
      - .:/www_root/
      - ./logs:/www_root/logs
      - ./src:/usr/src
    ports:
      - 8000:8000

volumes:
  static_volume:
  files_volume:
