# Generated by Django 3.1.13 on 2021-10-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='last_time_block',
        ),
    ]
