# Generated by Django 3.1.13 on 2021-11-24 21:10

import apps.core.users.models.User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211104_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dias_trabalhados',
            field=models.JSONField(),
        ),
        migrations.AddField(
            model_name='user',
            name='function',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
