# Generated by Django 3.1.13 on 2021-11-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211124_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='function',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
