# Generated by Django 3.1.13 on 2021-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211125_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dias_trabalhados',
            field=models.JSONField(default={}),
        ),
    ]
