# Generated by Django 3.1.13 on 2021-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211125_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dias_trabalhados',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
